# Generated by Django 5.1.4 on 2025-02-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useractivitylog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'دخول'), ('LOGOUT', 'حروج'), ('CREATE', 'انشاء'), ('UPDATE', 'تعديل'), ('DELETE', 'حذف'), ('VIEW', 'عرض'), ('DOWNLOAD', 'تحميل')], max_length=10, verbose_name='العملية'),
        ),
    ]
