# Generated by Django 5.1.4 on 2025-02-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_useractivitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
