# Generated by Django 5.1.4 on 2025-02-27 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_useractivitylog_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم المستند'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المستخدم'),
        ),
    ]
