# Generated by Django 5.1.4 on 2025-02-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_useractivitylog_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'دخول'), ('LOGOUT', 'خروج'), ('CREATE', 'انشاء'), ('UPDATE', 'تعديل'), ('DELETE', 'حذف'), ('VIEW', 'عرض'), ('DOWNLOAD', 'تحميل'), ('CONFIRM', 'تأكيد رسوم'), ('REJECT', 'رفض رسوم')], max_length=10, verbose_name='العملية'),
        ),
    ]
