# Generated by Django 5.1.4 on 2025-03-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_useractivitylog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='جهة العمل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
