# Generated by Django 5.1.4 on 2025-02-18 13:19

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'نوع شركة',
                'verbose_name_plural': 'انواع الشركات',
                'permissions': [('edit_sections', 'Can edit sections')],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=255, unique=True, verbose_name='الاسم بالانجليزية')),
                ('ar_name', models.CharField(max_length=255, unique=True, verbose_name='الاسم بالعربية')),
            ],
            options={
                'verbose_name': 'دولة',
                'verbose_name_plural': 'الدول',
                'permissions': [('edit_sections', 'Can edit sections')],
            },
        ),
        migrations.CreateModel(
            name='DecreeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='رقم الفئة')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم الفئة')),
            ],
            options={
                'verbose_name': 'الفئة',
                'verbose_name_plural': 'الفئات',
                'permissions': [('edit_sections', 'Can edit sections')],
            },
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'نوع مستند',
                'verbose_name_plural': 'انواع المستندات',
                'permissions': [('edit_sections', 'Can edit sections')],
            },
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'حكومة',
                'verbose_name_plural': 'الحكومات',
                'permissions': [('edit_sections', 'Can edit sections')],
            },
        ),
        migrations.CreateModel(
            name='Decree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='رقم القرار')),
                ('date', models.DateField(verbose_name='تاريخ القرار')),
                ('status', models.IntegerField(choices=[(1, 'قبول'), (2, 'رفض'), (3, 'سحب'), (4, 'الغاء')], default=1, verbose_name='حالة القرار')),
                ('applicant', models.CharField(blank=True, max_length=255, verbose_name='مقدم الطلب')),
                ('company', models.CharField(max_length=255, verbose_name='صاحب العلامة')),
                ('date_applied', models.DateField(verbose_name='تاريخ التقديم')),
                ('number_applied', models.IntegerField(blank=True, null=True, verbose_name='رقم القيد')),
                ('ar_brand', models.CharField(blank=True, max_length=255, verbose_name='العلامة (عربي)')),
                ('en_brand', models.CharField(blank=True, max_length=255, verbose_name='العلامة (انجليزي)')),
                ('pdf_file', models.FileField(blank=True, upload_to=documents.models.generate_random_filename, verbose_name='ملف القرار')),
                ('attach', models.FileField(blank=True, upload_to=documents.models.generate_random_filename, verbose_name='المرفقات')),
                ('notes', models.TextField(blank=True, max_length=999, verbose_name='ملاحظات')),
                ('is_published', models.BooleanField(default=False, verbose_name='تم اشهاره مبدئيا')),
                ('is_placeholder', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.country', verbose_name='الدولة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.decreecategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'قرار',
                'verbose_name_plural': 'قرارات',
                'ordering': ['-is_placeholder', '-id'],
                'permissions': [('download_doc', 'Can download a pdf')],
            },
        ),
        migrations.CreateModel(
            name='FormPlus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم')),
                ('date', models.DateField(blank=True, verbose_name='التاريخ')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('keywords', models.TextField(blank=True, max_length=999, verbose_name='التفاصيل')),
                ('pdf_file', models.FileField(blank=True, upload_to=documents.models.generate_random_filename)),
                ('word_file', models.FileField(blank=True, upload_to=documents.models.generate_random_filename)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.doctype', verbose_name='النوع')),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.government', verbose_name='الحكومة')),
            ],
            options={
                'verbose_name': 'نموذج او قرار',
                'verbose_name_plural': 'نماذج و قرارات',
                'ordering': ['-id'],
                'permissions': [('download_doc', 'Can download a pdf')],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('number', models.IntegerField(verbose_name='رقم التسجيل')),
                ('decree_number', models.IntegerField(verbose_name='رقم القرار')),
                ('applicant', models.CharField(max_length=255, verbose_name='طالب التسجيل')),
                ('owner', models.CharField(max_length=255, verbose_name='مالك العلامة')),
                ('address', models.CharField(max_length=255, verbose_name='العنوان')),
                ('date_applied', models.DateField(verbose_name='تاريخ التقديم')),
                ('ar_brand', models.CharField(max_length=255, verbose_name='العلامة (عربي)')),
                ('en_brand', models.CharField(max_length=255, verbose_name='العلامة (انجليزي)')),
                ('img_file', models.ImageField(blank=True, upload_to=documents.models.generate_random_filename, verbose_name='الصورة')),
                ('attach', models.FileField(blank=True, upload_to=documents.models.generate_random_filename, verbose_name='المرفقات')),
                ('e_number', models.IntegerField(verbose_name='رقم النشرية')),
                ('status', models.IntegerField(choices=[(1, 'نشر مبدئي'), (2, 'متنازع عليه'), (3, 'نشر نهائي'), (4, 'مسحوب')], default=1, verbose_name='حالة التسجيل')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='مخفي')),
                ('notes', models.TextField(blank=True, max_length=999, verbose_name='ملاحظات')),
                ('objection_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاعتراض')),
                ('is_objected', models.BooleanField(default=False, verbose_name='تم الاعتراض عليه')),
                ('created_at', models.DateTimeField(default=documents.models.default_created_at, verbose_name='تاريخ النشر')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.decreecategory', verbose_name='الفئة')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.country', verbose_name='الدولة')),
                ('decree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.decree', verbose_name='القرار')),
            ],
            options={
                'verbose_name': 'اشهار',
                'verbose_name_plural': 'اشهارات',
                'ordering': ['-id'],
                'permissions': [('gen_pub_pdf', 'Can generate a publication pdf'), ('pub_change_status', 'can change publication status from initial to final')],
            },
        ),
        migrations.CreateModel(
            name='Objection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='رقم المعارضة')),
                ('name', models.CharField(max_length=64, verbose_name='اسم ولقب مقدم الشكوى')),
                ('job', models.CharField(max_length=24, verbose_name='المهنة')),
                ('address', models.CharField(max_length=255, verbose_name='محل الاقامة')),
                ('phone', models.CharField(max_length=10, verbose_name='رقم الهاتف')),
                ('com_name', models.CharField(max_length=255, verbose_name='اسم الشركة المقدمة للشكوى')),
                ('com_address', models.CharField(max_length=255, verbose_name='عنوان الشركة')),
                ('com_og_address', models.CharField(max_length=255, verbose_name='عنوان المقر الرئيسي للشركة')),
                ('com_mail_address', models.CharField(max_length=255, verbose_name='عنوان البريد الرئيسي لاستلام المكاتبات المتعلقة بالمعارضة')),
                ('status', models.IntegerField(choices=[(1, 'معلق'), (2, 'موافقة'), (3, 'رفض')], default=1, verbose_name='حالة الاعتراض')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='اسباب الرفض')),
                ('pdf_file', models.FileField(blank=True, upload_to=documents.models.generate_random_filename, verbose_name='ملف الاعتراض')),
                ('notes', models.TextField(blank=True, max_length=999, verbose_name='تفاصيل')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم دفع الرسوم')),
                ('unique_code', models.CharField(editable=False, max_length=13, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاعتراض')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('com_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.comtype', verbose_name='غرض الشركة')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.country', verbose_name='الجنسية')),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.publication', verbose_name='الاشهار')),
            ],
            options={
                'verbose_name': 'اعتراض',
                'verbose_name_plural': 'اعتراضات',
                'ordering': ['-id'],
                'permissions': [('confirm_objection_fee', 'Can confirm objection fee payment')],
            },
        ),
    ]
