# Generated by Django 5.1.4 on 2025-02-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objection',
            options={'ordering': ['-id'], 'permissions': [('confirm_objection_fee', 'Can confirm objection fee payment')], 'verbose_name': 'اعتراض', 'verbose_name_plural': 'الاعتراضات'},
        ),
    ]
