# Generated by Django 5.1.4 on 2025-02-18 17:03

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_objection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='objection',
            name='receipt_file',
            field=models.FileField(blank=True, upload_to=documents.models.generate_random_filename, verbose_name='ايصال الدفع'),
        ),
    ]
