# Generated by Django 5.1.4 on 2025-02-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_objection_receipt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ تقديم الاعتراض'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='status',
            field=models.IntegerField(choices=[(1, 'في انتظار الدفع'), (2, 'في انتظار التأكيد'), (3, 'تم الدفع'), (4, 'موافقة'), (5, 'رفض')], default=1, verbose_name='حالة الاعتراض'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='number',
            field=models.IntegerField(verbose_name='رقم الاشهار'),
        ),
    ]
