# Generated by Django 5.1.4 on 2025-02-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_objection_created_at_alter_objection_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formplus',
            options={'ordering': ['-id'], 'permissions': [('download_doc', 'Can download a pdf')], 'verbose_name': 'تشريع او نموذج', 'verbose_name_plural': 'تشريعات و نماذج'},
        ),
    ]
