# Generated by Django 5.1.4 on 2025-02-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_decreecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formplus',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
    ]
