# Generated by Django 5.1.4 on 2025-02-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_formplus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='decree',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='تم الغاءه'),
        ),
        migrations.AddField(
            model_name='decree',
            name='is_withdrawn',
            field=models.BooleanField(default=False, verbose_name='تم سحبه'),
        ),
    ]
