# Generated by Django 5.1.4 on 2025-02-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_decree_is_canceled_decree_is_withdrawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='decree',
            name='number_canceled',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم القرار المسحوب او الملغي'),
        ),
    ]
