# Generated by Django 5.1.4 on 2025-02-27 14:11

import django.core.validators
import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_decree_number_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decree',
            name='applicant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مقدم الطلب'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='ar_brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العلامة (عربي)'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='attach',
            field=models.FileField(blank=True, upload_to=documents.models.generate_random_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='المرفقات'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.decreecategory', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='صاحب العلامة'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.country', verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='date_applied',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التقديم'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='en_brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العلامة (انجليزي)'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=documents.models.generate_random_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='ملف القرار'),
        ),
        migrations.AlterField(
            model_name='formplus',
            name='government',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.government', verbose_name='الحكومة'),
        ),
        migrations.AlterField(
            model_name='formplus',
            name='pdf_file',
            field=models.FileField(upload_to=documents.models.generate_random_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='ملف PDF'),
        ),
        migrations.AlterField(
            model_name='formplus',
            name='word_file',
            field=models.FileField(blank=True, upload_to=documents.models.generate_random_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])], verbose_name='ملف Word'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=documents.models.generate_random_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='ملف الاعتراض'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='attach',
            field=models.FileField(blank=True, upload_to=documents.models.generate_random_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='المرفقات'),
        ),
    ]
