# Generated by Django 5.1.4 on 2025-02-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_decree_attach_alter_decree_number_canceled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comtype',
            options={'verbose_name': 'نوع شركة', 'verbose_name_plural': 'انواع الشركات'},
        ),
        migrations.AlterModelOptions(
            name='decreecategory',
            options={'verbose_name': 'الفئة', 'verbose_name_plural': 'الفئات'},
        ),
        migrations.AlterModelOptions(
            name='doctype',
            options={'verbose_name': 'نوع مستند', 'verbose_name_plural': 'انواع المستندات'},
        ),
        migrations.AlterModelOptions(
            name='government',
            options={'verbose_name': 'حكومة', 'verbose_name_plural': 'الحكومات'},
        ),
    ]
