# Generated by Django 5.1.4 on 2025-02-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_comtype_options_alter_decreecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'دولة', 'verbose_name_plural': 'الدول'},
        ),
    ]
