# Generated by Django 5.1.4 on 2025-02-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decree',
            options={'ordering': ['-is_placeholder', '-id'], 'permissions': [('download_doc', ' تحميل الملفات ')], 'verbose_name': 'قرار', 'verbose_name_plural': 'قرارات'},
        ),
        migrations.AlterModelOptions(
            name='formplus',
            options={'ordering': ['-id'], 'permissions': [('download_doc', ' تحميل الملفات ')], 'verbose_name': 'تشريع او نموذج', 'verbose_name_plural': 'تشريعات و نماذج'},
        ),
        migrations.AlterModelOptions(
            name='objection',
            options={'ordering': ['-id'], 'permissions': [('confirm_objection_fee', ' قبول او رفض ايصال رسوم اعتراض '), ('confirm_objection_status', ' قبول او رفض اعتراض ')], 'verbose_name': 'اعتراض', 'verbose_name_plural': 'الاعتراضات'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-id'], 'permissions': [('gen_pub_pdf', ' انشاء PDF اشهار مبدئي '), ('pub_change_status', ' تغيير حالة إشهار من مبدئي الى نهائي ')], 'verbose_name': 'اشهار', 'verbose_name_plural': 'اشهارات'},
        ),
    ]
