# Generated by Django 5.1.4 on 2025-03-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_alter_decree_options_alter_formplus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='number_applied',
            field=models.IntegerField(default=1, verbose_name='رقم القيد'),
            preserve_default=False,
        ),
    ]
