# Generated by Django 5.1.4 on 2025-03-02 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_publication_number_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objection',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='ر.ت'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='decree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.decree', verbose_name='رقم القرار'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='number_applied',
            field=models.IntegerField(verbose_name='رقم التسجيل'),
        ),
    ]
